<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE thuvien [
    <!ELEMENT thuvien (sach+)>
    <!ELEMENT sach (title, author, year, genre)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT author (#PCDATA)>
    <!ELEMENT year (#PCDATA)>
    <!ELEMENT genre (#PCDATA)>
]>
<thuvien>
    <sach>
        <title>Đắc Nhân Tâm</title>
        <author>Dale Carnegie</author>
        <year>1936</year>
        <genre>Kỹ năng sống</genre>
    </sach>

    <sach>
        <title>Harry Potter và Hòn đá Phù thủy</title>
        <author>J.K. Rowling</author>
        <year>1997</year>
        <genre>Khoa học viễn tưởng</genre>
    </sach>

    <sach>
        <title>Nhà Giả Kim</title>
        <author>Paulo Coelho</author>
        <year>1988</year>
        <genre>Tiểu thuyết</genre>
    </sach>
</thuvien>
